AWSTemplateFormatVersion: 2010-09-09

Parameters:
  InstanceType:
    Description: EC2 Instance Type 
    Type: String 
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - m4.large

Resources:
  StackInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f3d9639a5674d559
      SecurityGroups: 
        - Ref: "InstanceSecurityGroup"

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp 
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: InstanceId of the EC2 Instance
    Value: {
        "Ref": "StackInstance"
      }
  PublicDNS:
    Description: Public DNSName of the EC2 instance
    Value: {
        "Fn::GetAtt": [
          "StackInstance",
          "PublicDnsName"
        ]
      }
  PublicIp:
    Description: Public IP address of the EC2 instance
    Value: {
        "Fn::GetAtt": [
          "StackInstance",
          "PublicIp"
        ]
      }


